### ISSUE TITLE
Suppress Media Item Detail Pages by Default

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/wp-alleyvate#10]
It is rarely the case that we want an attachment to have its own detail page publicly accessible, so this functionality should be turned off by default.

**Comment by dlh01** [comment]
Related: #4

**Comment by kevinfodness** [comment]
The difference between this and #4 is that this will prevent the URLs from existing at all. We'll need to collectively determine which route we want to go (or, perhaps, have an opinionated default but allow opting in to the other method).

**Comment by dlh01** [comment]
Folks can also contribute to https://core.trac.wordpress.org/ticket/57913 to get more support for controlling attachment pages into core.

**Comment by kevinfodness** [comment]
- Handle unattached media
- Handle attached media
- Remove link to attachment from media modal

**Comment by renatonascalves** [comment]
FYI: There is some prior art for disabling attachment routing [here](https://github.com/alleyinteractive/alleypack/blob/main/modules/disable-attachment-routing/1.0/readme.md).
