### ISSUE TITLE
[FEATURE]: Different Admin Color Scheme for prod vs. non-prod

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/wp-alleyvate#18]
### Description

Alleyvate should show different Core Admin Color Schemes active depending on the environment.

### Use Case

When an Alley user visits an admin area for a site, there isn't a clear and immediate indication that the admin area is for a production or non-production environments. Having a clear indication (such as a red Admin Color Scheme) will help to prevent Alley developers/users from confusing production for a non-production environment.

**Comment by jakewrfoster** [comment]
Issue originally raised by @dustinpaluch.

**Comment by vancoder** [comment]
I'd suggest that this should not be implemented in Alleyvate, as to me it seems counter to the Alleyvate philosophy (as I understand it) of _removing_ undesirable features. This would add effectively _add_ a feature - and one which could confuse clients (for instance, if the admin theme was intentionally being modified already).

**Comment by jakewrfoster** [comment]
@vancoder just to add a minor point of clarification "Admin Color Scheme" preferences are user-specific, so this wouldn't have an effect on how clients experience the WordPress admin area.

**Comment by kevinfodness** [comment]
This is implemented in a separate plugin already and doesn't need to be part of Alleyvate: https://github.com/alleyinteractive/wp-environment-switcher/
