### ISSUE TITLE
Disable `redirect_guess_404_permalink()`

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/wp-alleyvate#2]
This behavior often confuses clients.

**Comment by mboynes** [comment]
I think it's also non-performant and could potentially create load issues. Anecdotal data point: I haven't looked into it but noticed a nasty db query the other day in TheWrap caused by this function (url was something like `thewrap.com/a-` which created a wildcard query with a ton of results)

**Comment by scottnelle** [comment]
Noting that if we do this (and I would love for it to be the default), there's now a filter as of WP 5.5 to do so: `do_redirect_guess_404_permalink`. If we're nervous to make it the default, perhaps exposing a setting in Reading settings would be a good middle ground?
