### ISSUE TITLE
[FEATURE]: Meta inspector

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/wp-alleyvate#22]
### Description

Alley's [Meta Inspector](https://github.com/alleyinteractive/meta-inspector) plugin should be included with all of our projects, at least for non-production envs.

### Use Case

It is often the case that non-production envs are used for development and testing, in order to streamline troubleshooting, UAT, and other dev tasks, Meta Inspector should be included on those envs by default.

**Comment by jakewrfoster** [comment]
Issue originally raised by @juliobranha

**Comment by srtfisher** [comment]
Is it worth leaving this as apart of `create-wordpress-project` vs trying to bundle a plugin within this one?

**Comment by srtfisher** [comment]
Closing in favor of https://github.com/alleyinteractive/create-wordpress-project/issues/47.
