### ISSUE TITLE
[FEATURE]: Disable Apple News pushes on non-prod

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/wp-alleyvate#26]
### Description

Apple News shouldn't be allowed to publish anything from non-production environments.

### Use Case

It can be the case that developers on non-production environments are sending payloads to Apple News unknowingly, which can create further issues. Since there is little to no reason why a non-prod env should be sending data to Apple News, Alleyvate should disable the ability to do so from non-prod envs.

**Comment by jakewrfoster** [comment]
Issue originally raised by @emilyatmobtown

**Comment by mslinnea** [comment]
We have a site with a sandbox Apple News channel, but that seems uncommon.
