### ISSUE TITLE
[FEATURE]: Enable Query Monitor and Meta Inspector locally and on non-prod VIP envs

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/wp-alleyvate#29]
### Description

Alleyvate should enable Query Monitor on all non-production envs.

### Use Case

Query monitor is an invaluable diagnostic tool for WordPress development and should be enabled by default on all non-production environments so as to streamline development cycles.

**Comment by jakewrfoster** [comment]
Issue originally raised by @emilyatmobtown

**Comment by srtfisher** [comment]
Should be handled in https://github.com/alleyinteractive/create-wordpress-project/
