### ISSUE TITLE
[FEATURE] Disable deep pagination

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wp-alleyvate#42]
### Description

Disable pagination past page 100 (filter the value to allow sites to customize it).

### Use Case

Deep pagination using offsets is slow, both in ES and MySQL. Rarely would a human navigate to page 6500 of search results, of a section, etc. Spiders, on the other hand, _do_ page that deep and can cause performance issues for a site.

### Additional Notes

* Only apply to frontend queries; admin queries should not be limited
* Should apply to _unauthenticated_ REST requests, but not _authenticated_ ones
* Should apply to anything paginated, not just posts. This mainly applies to REST requests, as there's no (core) requests for listing users, terms, etc.

**Comment by mslinnea** [comment]
What do you think should happen for queries beyond page 100?  Would admin queries be allowed?  All queries, or just the main query?  

One thing to consider is the SEO impact of duplicate content.  Perhaps a redirect should be placed, or a 404?
