### ISSUE TITLE
Spike: Limit access to XML-RPC

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wp-alleyvate#50]
### Description

It would be helpful to block XML-RPC access as much as possible. Jetpack uses it, as do the WordPress.com mobile apps, so we shouldn't block it completely. Maybe we can get away with blocking basic auth?

We should spike this first to list out our options.

### Use Case

XMLRPC is a common attack vector for hackers/bot networks to brute force login attempts. Anything we can do to mitigate that is a win for security, server performance, chargeable server requests, etc.

### Acceptance Criteria

- Research what our options are for either fully disabling XMLRPC or selectively allowing access to it (e.g., for Jetpack or WordPress.com mobile apps)
- Create a follow-up issue with the details to build the feature

**Comment by kevinfodness** [comment]
What do the VIP mu-plugins do with regard to securing this already? What about what VIP is doing at the network level?

**Comment by srtfisher** [comment]
I previously limited XML-RPC access and only allowed Jetpack through with some prior art here: https://l.alley.dev/af5db9ec9c

**Comment by jakewrfoster** [comment]
cc @kevinfodness https://github.com/Automattic/vip-go-mu-plugins-built/blob/af4e4e21f9a6e5cb4aa7134391eb3d4c2b2667da/vip-helpers/vip-utils.php#L1509-L1537

it looks like the solution sean shared above is pretty close to what VIP is doing.
