### ISSUE TITLE
Remove dashboard widgets

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/wp-alleyvate#7]
Originally reported by @srtfisher in an internal repo:

> Remove commonly unused and sometimes bad-performing dashboard widgets, including:
> Quick Draft
> WordPress Events and News
> Jetpack Stats

**Comment by vancoder** [comment]
I have WIP for this.

**Comment by dlh01** [comment]
@vancoder It's a little outside the original scope of this ticket, but would it be feasible to also disable the "Custom Fields" meta box as part of this work? This happens currently in Alley's starter theme (`inc/admin.php`), but now that our repos are rooted in `wp-content`, and since the motivation is the same as these Dashboard widgets, it seems incongruous to have the logic in the theme.

**Comment by vancoder** [comment]
> @vancoder It's a little outside the original scope of this ticket, but would it be feasible to also disable the "Custom Fields" meta box as part of this work? This happens currently in Alley's starter theme (`inc/admin.php`), but now that our repos are rooted in `wp-content`, and since the motivation is the same as these Dashboard widgets, it seems incongruous to have the logic in the theme.

I'd be inclined to handle non-dashboard widgets separately, as they are feel like a different context to me, and also fire on different hooks. Open to debate though.

**Comment by vancoder** [comment]
PR in CR.
