### ISSUE TITLE
Pantheon site protocol scheme should match the db value regardless of request type

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/wp-alleyvate#85]
### Description

Pantheon-maintains a [wp-config-pantheon.php file](https://github.com/pantheon-systems/WordPress/blob/default/wp-config-pantheon.php#L52-L65) that manipulates protocol scheme for HTTP requests. The file defaults to `http` unless `HTTP_USER_AGENT_HTTPS` is set and has the value of `on`. Obviously, this won't fire for CLI commands, which can create an issue wherein CLI (and other non-http) requests return the wrong protocol.

### Use Case

When non-http requests are made to pantheon sites (via WPCLI or cron, for example), the site's domain protocol matches the protocol in the database options for `siteurl` and `home`.

**Comment by anubisthejackle** [comment]
@jakewrfoster Do we want to replace the protocol scheme if the `WP_SITEURL` and / or `WP_HOME` constants are used, but leave the rest of the constant, or do we want to completely rely on the database value and ignore the constants?

**Comment by anubisthejackle** [comment]
Also, do we want to restrict this change to Pantheon only?
